-- Face Services shared attendance schema.
-- This file defines the shared `staffs` and `attendances` tables used by
-- Face_Services to look up employees and record check-in/check-out events.

CREATE TABLE IF NOT EXISTS staffs (
    -- `employee_id` is generated by the business system, for example `NV001`.
    -- It is not AUTO_INCREMENT because the external format may include prefixes.
    employee_id VARCHAR(20) PRIMARY KEY,

    full_name VARCHAR(100) NOT NULL,
    department VARCHAR(100) NULL,
    position VARCHAR(100) NULL,
    onboard_date DATE NULL,

    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',

    phone VARCHAR(20) NULL,
    personal_email VARCHAR(100) NULL,
    national_id VARCHAR(20) NULL,
    bank_account VARCHAR(30) NULL,
    bank_name VARCHAR(100) NULL,
    date_of_birth DATE NULL,

    -- Default password is derived from date_of_birth by the account-management
    -- flow, but only the hash is stored here. Never store the plain password.
    -- Example policy: 1998-04-21 -> default password `21041998` -> bcrypt hash.
    password_hash VARCHAR(255) NULL,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_staffs_status (status),
    INDEX idx_staffs_department (department),
    UNIQUE KEY uq_staffs_national_id (national_id),
    UNIQUE KEY uq_staffs_personal_email (personal_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendances (
    employee_id VARCHAR(20) NOT NULL,
    type ENUM('checkin', 'checkout') NOT NULL,

    -- Full check-in/check-out timestamp calculated by the application.
    check_time DATETIME NOT NULL,

    -- Attendance date is calculated by the application timezone
    -- (`attendance.timezone`, for example `Asia/Ho_Chi_Minh`) rather than
    -- relying on the database server's current date.
    check_date DATE NOT NULL,

    -- TRUE means the attendance event is on time:
    -- check-in not late, or check-out not early.
    on_time BOOLEAN NOT NULL,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- One employee can have at most one check-in and one check-out per day.
    -- This primary key also prevents race conditions when multiple frames
    -- attempt to insert the same attendance event at nearly the same time.
    PRIMARY KEY (employee_id, type, check_date),

    CONSTRAINT fk_attendances_staffs
        FOREIGN KEY (employee_id) REFERENCES staffs(employee_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    INDEX idx_attendances_date (check_date),
    INDEX idx_attendances_employee_date (employee_id, check_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
